# Copyright 2024 Canonical Ltd.
# See LICENSE file for licensing details.

options:
  expose-external:
    description: |
      String to determine how to expose the MySQLRouter externally from the Kubernetes cluster.
      Possible values: 'false', 'nodeport', 'loadbalancer'
    type: string
    default: "false"

  loadbalancer-extra-annotations:
    description: |
      A JSON string representing extra annotations for the Kubernetes service created
      and managed by the charm.
    type: string
    default: "{}"
