on:
  workflow_call:
    inputs:
      artifact-prefix:
        description: |
          Prefix for charm package GitHub artifact(s)
          
          Use canonical/data-platform-workflows build_charm.yaml to build the charm(s)
        required: true
        type: string

jobs:
  collect-integration-tests:
    name: Collect integration test spread jobs
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up environment
        run: sudo snap install charmcraft --classic --channel latest/candidate
      - name: Collect spread jobs
        id: collect-jobs
        shell: python
        run: |
          import json
          import os
          import subprocess

          spread_jobs = (
              subprocess.run(
                  ["charmcraft", "test", "--list", "github-ci"], capture_output=True, check=True, text=True
              )
              .stdout.strip()
              .split("\n")
          )
          jobs = []
          for job in spread_jobs:
              # Example `job`: "github-ci:ubuntu-24.04:tests/spread/test_charm.py:juju36"
              _, runner, task, variant = job.split(":")
              # Example: "test_charm.py"
              task = task.removeprefix("tests/spread/")
              if runner.endswith("-arm"):
                  architecture = "arm64"
              else:
                  architecture = "amd64"
              # Example: "test_charm.py:juju36 | amd64"
              name = f"{task}:{variant} | {architecture}"
              # ":" character not valid in GitHub Actions artifact
              name_in_artifact = f"{task}-{variant}-{architecture}"
              jobs.append({
                  "spread_job": job,
                  "name": name,
                  "name_in_artifact": name_in_artifact,
                  "runner": runner,
              })
          output = f"jobs={json.dumps(jobs)}"
          print(output)
          with open(os.environ["GITHUB_OUTPUT"], "a") as file:
              file.write(output)
    outputs:
      jobs: ${{ steps.collect-jobs.outputs.jobs }}

  integration-test:
    strategy:
      fail-fast: false
      matrix:
        job: ${{ fromJSON(needs.collect-integration-tests.outputs.jobs) }}
    name: ${{ matrix.job.name }}
    needs:
      - collect-integration-tests
    runs-on: ${{ matrix.job.runner }}
    timeout-minutes: 200 # TODO
    steps:
      - name: Free up disk space
        timeout-minutes: 1
        run: |
          printf '\nDisk usage before cleanup\n'
          df --human-readable
          # Based on https://github.com/actions/runner-images/issues/2840#issuecomment-790492173
          rm -r /opt/hostedtoolcache/
          printf '\nDisk usage after cleanup\n'
          df --human-readable
      - name: Checkout
        timeout-minutes: 3
        uses: actions/checkout@v4
      - name: Set up environment
        timeout-minutes: 5
        run: sudo snap install charmcraft --classic --channel latest/candidate
      - name: Download packed charm(s)
        timeout-minutes: 5
        uses: actions/download-artifact@v4
        with:
          pattern: ${{ inputs.artifact-prefix }}-*
          merge-multiple: true
      - name: Run spread job
        timeout-minutes: 180
        id: spread
        run: charmcraft test '${{ matrix.job.spread_job }}'
      - timeout-minutes: 1
        if: ${{ success() || (failure() && steps.spread.outcome == 'failure') }}
        run: snap list
      - name: Select model
        timeout-minutes: 1
        # `!contains(matrix.job.spread_job, 'juju29')` workaround for juju 2 error:
        # "ERROR cannot acquire lock file to read controller concierge-microk8s: unable to open
        # /tmp/juju-store-lock-3635383939333230: permission denied"
        # Unable to workaround error with `sudo rm /tmp/juju-*`
        if: ${{ !contains(matrix.job.spread_job, 'juju29') && (success() || (failure() && steps.spread.outcome == 'failure')) }}
        id: juju-switch
        run: |
          # sudo needed since spread runs scripts as root
          sudo juju switch test
          mkdir ~/logs/
      - name: juju status
        timeout-minutes: 1
        if: ${{ !contains(matrix.job.spread_job, 'juju29') && (success() || (failure() && steps.spread.outcome == 'failure')) }}
        run: sudo juju status --color --relations | tee ~/logs/juju-status.txt
      - name: juju debug-log
        timeout-minutes: 3
        if: ${{ !contains(matrix.job.spread_job, 'juju29') && (success() || (failure() && steps.spread.outcome == 'failure')) }}
        run: sudo juju debug-log --color --replay --no-tail | tee ~/logs/juju-debug-log.txt
      - name: jhack tail
        timeout-minutes: 3
        if: ${{ !contains(matrix.job.spread_job, 'juju29') && (success() || (failure() && steps.spread.outcome == 'failure')) }}
        run: sudo jhack tail --printer raw --replay --no-watch | tee ~/logs/jhack-tail.txt
      - name: Upload logs
        timeout-minutes: 5
        if: ${{ !contains(matrix.job.spread_job, 'juju29') && (success() || (failure() && steps.spread.outcome == 'failure')) }}
        uses: actions/upload-artifact@v4
        with:
          name: logs-integration-test-${{ matrix.job.name_in_artifact }}
          path: ~/logs/
          if-no-files-found: error
      - name: Disk usage
        timeout-minutes: 1
        if: ${{ success() || (failure() && steps.spread.outcome == 'failure') }}
        run: df --human-readable
