# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.
name: Release to Charmhub

on:
  push:

jobs:
  ci-tests:
    uses: ./.github/workflows/ci.yaml

  build:
    name: Build charm
    uses: canonical/data-platform-workflows/.github/workflows/build_charm.yaml@artifact-v4
    with:
      charmcraft-snap-channel: beta

  release:
    name: Release charm
    needs:
      - build
    uses: canonical/data-platform-workflows/.github/workflows/release_charm.yaml@artifact-v4
    with:
      channel: 8.0/edge/test
      artifact-prefix: ${{ needs.build.outputs.artifact-prefix }}
      create-github-release: false
    secrets:
      charmhub-token: ${{ secrets.CHARMHUB_TOKEN }}
